### ISSUE TITLE
Render special links in the way some sites link themselves, like Github, Gitlab, Reddit

### ISSUE THREAD

**Issue by autoferrit** [dragonwocky/notion-enhancer#112]
My feature request, is to link to certain sites in a manner that is recognizable to those that use that site. For example. If I link to a reddit page such as `https://reddit.com/r/notion` it renders, or shows inline as `/r/notion`

Likewise, for others:
Github: `https://github.com/dragonwocky/notion-enhancer` -> `dragonwocky/notion-enhancer`
or
`https://github.com/dragonwocky/notion-enhancer` -> [:octocat:dragonwocky/notion-enhancer](https://github.com/dragonwocky/notion-enhancer) 
and the same with gitlab. I think using their favicon would work well enough to use as an icon too. But this is also if they decide to just put in a link, and not embed a bookmark.

**solution**
This could possibly work with the double brackets surrounding links? [[like this]]

**alternatives (optional)**
those sites reddit, github, gitlab, do this themselves (maybe minus the favicon). So this would make it more recognizable to where the link is going to.

**Comment by dragonwocky** [comment]
I've done some concept work/experiments with this...

a) to be compatible with different colour themes you can't just use the favicon (at least for github) - this isn't too much of a problem.
b) to stop this from interfering with custom-named links it can only be made to apply to links where the link text matches the link url - this is a requirement.
c) if you edit a block containing a link that has been enhanced the modified text is saved to notion (e.g. `dragonwocky/notion-enhancer` instead of `https://github.com/dragonwocky/notion-enhancer`) and the favicon gets removed - this breaks being able to re-apply changes.

This just doesn't really seem compatible with how Notion's built-in linking works.
