### ISSUE TITLE
Page name in new tab feature

### ISSUE THREAD

**Issue by atticus82** [dragonwocky/notion-enhancer#200]
Hi!
It is a great work you are doing with this Enhancer. I am using it since I knew it exists. One of the features I've been waiting is the multiple tabs in the same window, I really appreciate, but I miss something that probably you already are thinking of it: Put the name of the page in each tab. Right now in any tab always shows "notion.so". 
I'll be waiting for many other features. 
Kind regards,

**Comment by dragonwocky** [comment]
For most users, it does show the page name. Showing "notion.so" is a bug. 

Please add more information to https://github.com/dragonwocky/notion-enhancer/issues/196 with what platform you are on and screenshots of what you get when you open the devtools consoles (on mac `cmd+option+i` and `alt+cmd+option+i`, otherwise `ctrl+shift+i` and `alt+ctrl+shift+i`).
