### ISSUE TITLE
Syntax Error when running customiser.py

### ISSUE THREAD

**Issue by kaylamillerdev** [dragonwocky/notion-enhancer#24]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

I'm running 'python customiser.py' in the command prompt and getting a syntax error. (see screenshot below).

**expected behaviour**
why is this a bug - what should be happening?

Shouldn't be getting an error

**screenshots**
if applicable, add screenshots of your problem.

![image](https://user-images.githubusercontent.com/52870645/87689747-94748300-c756-11ea-9997-f20664c51dee.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
Windows 10

**Comment by kaylamillerdev** [comment]
![image](https://user-images.githubusercontent.com/52870645/87691300-73149680-c758-11ea-8c5b-2c9c39d2161f.png)

I also opened up the cleaner file in Visual Studio Code and it also has an error. I think it's because of differences between Python 2 and 3 but I am not familiar at all with Python.

**Comment by kaylamillerdev** [comment]
PS: when I disable the Python linter, VSCode doesn't say there are any problems, but it still gives the same exact error messages.

**Comment by dragonwocky** [comment]
what version of python are you running? in theory that error should only be occurring on python 2, though a couple people have reported weird stuff on python 3.8 that i haven't been able to reproduce yet.

for lines that `print()`/log something, you can probably just delete them. otherwise you might need to translate the f-strings into normal strings with concatenation (just `'text ' + variable` instead of `f'text variable'`).

this is already fixed in the wip update (see the js branch), so to minimise branch conflicts and leave me able to get this done asap I'm not committing any bugfixes to the master branch yet.

**Comment by kaylamillerdev** [comment]
I have python 2 and 3.8 installed. I'm not sure which one it's trying to use.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dragonwocky** [comment]
if you just run the `python` command alone to enter the shell it'll print the version up the top: if it says anything below 3.6 you may need to run with `python3` instead

**Comment by kaylamillerdev** [comment]
Installing the windows store python fixed it!
