### ISSUE TITLE
Implementation of Electron Tabs

### ISSUE THREAD

**Issue by Eldhrimer** [dragonwocky/notion-enhancer#84]
_I'm not sure if this is doable, or if it is outside of the scope of this enhancer._ 

### Problem
With the New Window addition in the tray menu, wich it is incredibly useful, now I have 3-6 Notion windows opened at the same time. Everyone minimizes at the same time with the key shorcut, and it's sometimes kinda messy when I try to find wich one I was using given that with no titlebar none have the name easily accesible.

### Solution
Using [Electron Tabs](https://github.com/brrd/electron-tabs) would fix this and rise the usability of the app to be on par with using in a browser, and boosting productivity.

### Alternatives
I couldn't think of any. Open to suggestions!

**Comment by dragonwocky** [comment]
[already planned](https://github.com/dragonwocky/notion-enhancer/blob/master/CHANGELOG.md#changelog) - would be pretty difficult to do, though, so it's lower down on my todo list than most of the other features/bugs at the moment.

**Comment by dragonwocky** [comment]
done some testing... it's not gonna work to just stick in electron tabs. going to have to write my own solution... this will take a while.

**Comment by dragonwocky** [comment]
this is ready for beta-testing: install a dev build as described [here](https://github.com/dragonwocky/notion-enhancer/blob/master/CONTRIBUTING.md#testing) and enable it under the core module.

I'll split it out into a separate module and add keyboard shortcuts for opening/closing tabs etc. later

**Comment by Eldhrimer** [comment]
First impressions:

- It's sweet. Powers up the productivity of the desktop app by tens of times. A comparable feature, in terms of productivity, to me would be offline use.
- Without the shorcuts it's a bit confusing, I found myself pressing ctrl+t a couple of times, but that speaks for how intuitive is this enhancement.
- Overall it feels fitting, and the enhancer logo on the upper left its just amazing.

Some comments:

- It should be kept as a part of core to me. This is a feature that alone will drive people to the enhancer, it's no small css trick. Maybe don't enabled by default, but for me it is on par with the no-titlebar feature, and deserves to be part and be promoted as part of the core.
- The shorcuts should be either the standard ones of every browser, or configurable.
- It would be rad to be able to choose a default page to open on the new tab. Don't know if it is doable.
- The name of the window stays as "Notion desktiop" instead of the name of the page you have open inside Notion. I don't see this as a problem but some may. Maybe use the name of the tab on foreground?
- The enhancer logo on the upper left could be turned into a button to open the enhancer? I don't know why exactly but it would be cool.

_All this testing has been done in Manjaro linux using the AUR notion-app package_

**Comment by dragonwocky** [comment]
Interesting. That's the precise reason I want to put it into a separate module - it's such a big feature that I don't want it to get lost in the numerous options under that core, most of which don't have a lot of extra information about provided. It being in a separate module would also make it a lot clearer/easier to have configurable options (e.g. keyboard shortcuts). I will give it the #core tag, though, so it's pinned to the top of the list.

As for the other comments, definitely all good ideas. I'll see what I can do.

**Comment by dragonwocky** [comment]
All keyboard shortcuts should now be working + the other suggested features.

**Comment by Eldhrimer** [comment]
You really work hard. I love it!

**Comment by Eldhrimer** [comment]
Couple of other comments.
- sidetab is open/closed on a per tab basis. Which for me is sweet, maybe someone would find it annoying. If this could be configurable, nice. 
- ctrl+click still opens a page in a new window instead of a new tab. Middle click in a page does nothing, but would be sweet to open a new tab this way. 
- Middle click in a tab should close it (to keep the behaviour in par with that of a browser)
- The name of the window lags behind and doesn't always change when switching tabs. 

Everything else I just love it!

**Comment by dragonwocky** [comment]
The sidebar is considered part of the tab, rather than a separate menu, so I'll leave it as-is. New tabs will copy the state of the last one (e.g. if the sidebar is hidden then the next tab you open will also have the sidebar hidden).
Window name lag should be fixed + middle clicking tabs to close works (will push the changes when I'm not behind a proxy).

I'll see what I can do about capturing links...

**Comment by dragonwocky** [comment]
Links opened with `ctrl+click` are now captured by a new tab, but while testing stuff for middle clicking links I've discovered it actually does serve a purpose, albeit a small one: middle clicking will bypass preview and go straight into a page. It might cause some odd behaviour if I try to override current click handlers (they're handled by the obfuscated notion website code that my computer is not powerful enough to read without lagging out), so I'll leave that as is.

Investigating now if there's a way to make links opened via `notion://` end up in a new tab instead of overriding the window.

**Comment by fabiosangregorio** [comment]
Hi @dragonwocky, I love the implementation: really helps keeping the windows organized and it's a productivity boost. (please Notion hire this man :D )

Some things I noticed while testing it:
* enhancement: let the user drag a tab to a new window, just like Google Chrome tabs
* enhancement: let the user drag a tab to another group of tabs
* bug: if I create a new tab and click the "x" to close it BEFORE it has finished loading, the page closes but the tab stays there, broken and unusable.

**Comment by dragonwocky** [comment]
Tabs are now cross-window draggable (though this requires reloading them), and tabs will no longer break when you try close them.
Not sure what you mean by "group of tabs" @fabiosangregorio? If it's [something like the ones Chrome has](https://blog.google/products/chrome/manage-tabs-with-google-chrome/), then that's a no - if you really need to "group" your tabs use multiple windows.

**Comment by fabiosangregorio** [comment]
> Not sure what you mean by "group of tabs" @fabiosangregorio?

Hi @dragonwocky , what I meant is cross-window draggable tabs, and it works like a charm! Thank you very much.

> enhancement: let the user drag a tab to a new window, just like Google Chrome tabs

What I meant by this is: in Chrome you can drag a tab away from the active window, and it will automatically create a new window from that floating tab.
This is not essential, but it would be the cherry on top :)

**Comment by Eldhrimer** [comment]
Talking about cherries on top, if you @dragonwocky could look about the default page to open on a new tab I mentioned in my first comment it would be amazing. Completely not necessary

**Comment by dragonwocky** [comment]
@Eldhrimer I've already done that, I've just put the option under the core module because it works without tabs too.

**Comment by Eldhrimer** [comment]
Ah good! I didn't see it

**Comment by Eldhrimer** [comment]
Ah, a couple of request more before the next release if possible. Pinned tabs and favicons on the tab. Those will be awesome

Cheers

**Comment by dragonwocky** [comment]
pinned tabs and dragging into a new window might be features for another time: they can get a bit complicated particularly in terms of the making-them-not-duplicate-everything and of the UI. otherwise, I'm marking this as done.

**Comment by pranjalshah9814ps** [comment]
Hi @dragonwocky, loving this implementation of tabs and v0.10.0 in general.

However with the introduction of favicons, I ran into a **bug**:-
The window title shows the html <img> tag instead of the page icon favicon as is shown in the tab title. This can cause some confusion when switching between windows. Maybe have the window title without the favicon. I'm using Windows 10 BTW.
_Screenshot showing bug:-_
![Window title with <img> tag](https://user-images.githubusercontent.com/62697064/97571429-cbbd2600-1a0d-11eb-91bd-6b1593cd6fc3.png)

Also, I had an **enhancement** in mind especially for people using smaller screens:-
Allow the user to set the tab height and/or tab font size. I personally find that Chrome has a good tab height and tab font size which shows information well but doesn't take up to much screen space. However others may have their own preferences and hence I suggest that this be user customisable. This is completely not necessary but would be really great.

Really loving how this release is shaping up regardless. Cheers!
