### ISSUE TITLE
Support for davidbailey00/notion-deb-builder

### ISSUE THREAD

**Issue by naveenjohnsonv** [dragonwocky/notion-enhancer#93]
I'm on Pop!OS based on Ubuntu 20.04 LTS

Installed Notion as a .deb package built through https://github.com/davidbailey00/notion-deb-builder

Location:
/usr/bin/notion-desktop
I'm not particularly sure about it's file structure. It's built as a debian package so it must be similar to those. [Here](https://del.dog/stapingese.txt)'s an output of dpkg -L 

app.asar? electron.asar is located at /usr/lib/notion-desktop/resources/electron.asar

I prefer a debian install over other methods for linux. Also I can update the app myself though the deb-builder so I'm not dependent on the repo dev to release. This one also builds optionally from the mac or windows release. I prefer the windows one for it's keyboard shortcuts.

**Comment by dragonwocky** [comment]
I'm pretty sure the keyboard shortcuts are the same?
The [notion-app](https://github.com/jaredallard/notion-app) package similarly allows for picking which notion version/self-updating. You're not dependent on the repo dev. It's easy for the enhancer to support because it has an `app.asar`, the same as the official builds, while notion-deb-builder does some extraction and stuff itself, which makes installation/uninstallation unreliable.

**Comment by naveenjohnsonv** [comment]
Right, I'm using the [notion-app](https://github.com/jaredallard/notion-app) package now. Works well.
